Check
natalia-matash/input pull request #2
Opened 2023-03-23 08:51 UTC by Stanislav-Matash

https://stanislav-matash.github.io/input/

2023-03-23 08:56 UTC, natalia-matash requested changes
перероби зображення щоб було і транзишен

2023-03-23 08:56 UTC, natalia-matash commented on src/style.css
> +  background-image: url(Vector.png);
немає зображення

2023-03-23 08:56 UTC, natalia-matash commented on src/style.css
> +}
додай transition

2023-03-27 20:34 UTC, Stanislav-Matash commented
> https://stanislav-matash.github.io/input/

check

2023-03-27 20:43 UTC, natalia-matash approved these changes
Good job!

2023-03-27 20:43 UTC, merged